name: Build Grade Architect APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: master
          command: android debug
          repository_root: .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Fixed the Deprecation Error here
        with:
          name: GradeArchitect-Package
          path: bin/*.apk
